# Generated by Django 2.2.9 on 2020-05-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200528_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name_plural': 'Комментарии'},
        ),
    ]
